import { Language } from "./types";

export const languages: Record<string, Language> = {
    en: {
        label: "English",
        code: "en",
        texts: {
            search: "Search",
            city: "City",
            date: "Date",
            temperature: "Temperature",
            condition: "Condition",
            humidity: "Humidity",
            wind: "Wind",
            chanceOfRain: "Chance of Rain",
            precipitation: "Precipitation",
            snow: "Snow",
            chanceOfSnow: "Chance of Snow",
            celcius: "Celsius (°C)",
            fahrenheit: "Fahrenheit (°F)",
            error: "Something went wrong. Please check the city and date.",
        },
    },
    fr: {
        label: "Français",
        code: "fr",
        texts: {
            search: "Chercher",
            city: "Ville",
            date: "Date",
            temperature: "Température",
            condition: "Condition",
            humidity: "Humidité",
            wind: "Vent",
            chanceOfRain: "Probabilité de pluie",
            precipitation: "Précipitations",
            snow: "Neige",
            chanceOfSnow: "Probabilité de neige",
            celcius: "Celsius (°C)",
            fahrenheit: "Fahrenheit (°F)",
            error: "Une erreur s'est produite. Vérifiez la ville et la date.",
        },
    },
    es: {
        label: "Español",
        code: "es",
        texts: {
            search: "Buscar",
            city: "Ciudad",
            date: "Fecha",
            temperature: "Temperatura",
            condition: "Condición",
            humidity: "Humedad",
            wind: "Viento",
            chanceOfRain: "Probabilidad de lluvia",
            precipitation: "Precipitación",
            snow: "Nieve",
            chanceOfSnow: "Probabilidad de nieve",
            celcius: "Celsius (°C)",
            fahrenheit: "Fahrenheit (°F)",
            error: "Algo salió mal. Por favor, verifica la ciudad y la fecha.",
        },
    },
    de: {
        label: "Deutsch",
        code: "de",
        texts: {
            search: "Suchen",
            city: "Stadt",
            date: "Datum",
            temperature: "Temperatur",
            condition: "Wetterlage",
            humidity: "Luftfeuchtigkeit",
            wind: "Wind",
            chanceOfRain: "Regenwahrscheinlichkeit",
            precipitation: "Niederschlag",
            snow: "Schnee",
            chanceOfSnow: "Schneewahrscheinlichkeit",
            celcius: "Celsius (°C)",
            fahrenheit: "Fahrenheit (°F)",
            error: "Etwas ist schiefgelaufen. Bitte überprüfen Sie Stadt und Datum.",
        },
    },
    ta: {
        label: "தமிழ்",
        code: "ta",
        texts: {
            search: "தேடு",
            city: "நகர்",
            date: "தேதி",
            temperature: "வெப்பநிலை",
            condition: "நிலைமை",
            humidity: "ஊடுருவல்",
            wind: "காற்று",
            chanceOfRain: "மழை வாய்ப்பு",
            precipitation: "வீழ்ச்சி",
            snow: "பனிக்கட்டி",
            chanceOfSnow: "பனிக்கட்டி வாய்ப்பு",
            celcius: "செல்சியஸ் (°C)",
            fahrenheit: "ஃபாரன்ஹீட் (°F)",
            error: "ஏதோ தவறு ஏற்பட்டுள்ளது. நகரம் மற்றும் தேதியை சரிபார்க்கவும்.",
        },
    },
    zh: {
        label: "中文 (简体)",
        code: "zh",
        texts: {
            search: "搜索",
            city: "城市",
            date: "日期",
            temperature: "温度",
            condition: "天气状况",
            humidity: "湿度",
            wind: "风",
            chanceOfRain: "降雨概率",
            precipitation: "降水量",
            snow: "雪",
            chanceOfSnow: "降雪概率",
            celcius: "摄氏度 (°C)",
            fahrenheit: "华氏度 (°F)",
            error: "发生错误。请检查城市和日期。",
        },
    },
    ar: {
        label: "العربية",
        code: "ar",
        texts: {
            search: "بحث",
            city: "المدينة",
            date: "التاريخ",
            temperature: "درجة الحرارة",
            condition: "الحالة",
            humidity: "رطوبة",
            wind: "الرياح",
            chanceOfRain: "فرصة هطول الأمطار",
            precipitation: "هطول",
            snow: "ثلج",
            chanceOfSnow: "فرصة تساقط الثلوج",
            celcius: "سيليسيوس (°C)",
            fahrenheit: "فهرنهايت (°F)",
            error: "حدث خطأ ما. يرجى التحقق من المدينة والتاريخ.",
        },
    },
};

export type LanguageCode = keyof typeof languages;
